version: 2.0

sources:
  - name: sunglass_store_raw
    database: ETL
    schema: sunglass_store_raw
    tables:
      - name: users
        description: "Table containing user information"
        columns:
          - name: user_id
            description: "Unique identifier for each user"
          - name: first_name
            description: "First name of the user"
          - name: last_name
            description: "Last name of the user"
          - name: email
            description: "Email address of the user"
          - name: age
            description: "Age of the user"
          - name: gender
            description: "Gender of the user"
          - name: country
            description: "Country of residence of the user"
          - name: post_code
            description: "Postal code of the user's address"
          - name: join_date
            description: "Date when the user joined the platform"
          - name: from_platform
            description: "Platform from which the user joined (e.g., web, mobile)"

      - name: products
        description: "Table containing product information"
        columns:
          - name: item_id
            description: "Unique identifier for each product"
          - name: product_name
            description: "Name of the product"
          - name: brand
            description: "Brand of the product"
          - name: price
            description: "Price of the product"
          - name: lens_color
            description: "Color of the lens"
          - name: eye_size
            description: "Size of the eye wear"
          - name: polarized_glasses
            description: "Indicates if the product has polarized glass (true/false)"
          - name: prescribed_glasses
            description: "Indicates if the product is prescribed glass (true/false)"
          - name: is_active
            description: "Indicates if the product is currently active (true/false)"
          - name: list_date
            description: "Date when the product was listed on the platform"
          - name: discontinued_date
            description: "Date when the product was discontinued, if applicable"
          
      - name: orders
        description: "Table containing order information"
        columns:
          - name: order_id
            description: "Unique identifier for each order"
          - name: user_id
            description: "Identifier for the user who placed the order"
          - name: item_id
            description: "Identifier for the product ordered"
          - name: purchase_date
            description: "Date when the order was placed"
          - name: payment_type
            description: "Type of payment used for the order (e.g., credit card, paypal, google pay)"

      - name: interaction
        description: "Table containing user interaction information"
        columns:
          - name: interaction_id
            description: "Type of interaction (e.g., view, click, add to cart)"
          - name: user_id
            description: "Identifier for the user who interacted with the product"
          - name: item_id
            description: "Identifier for the product that was interacted with"
          - name: interaction_date
            description: "Date when the interaction occurred"
      
      - name: interaction_types
        description: "Table containing interaction type information"
        columns:
          - name: interaction_id
            description: "Unique identifier for each interaction type"
          - name: interaction_type
            description: "Type of interaction (e.g., view, click, add to cart)"
